# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170421_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.SiteUser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=200),
        ),
    ]
