# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170423_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['date_added', 'playlist']},
        ),
    ]
