# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-date_created']},
        ),
    ]
